# TEST Environment Configuration

# OAuth Token Configuration
oauth.token.host=itiampingtest.cloud.pge.com
oauth.token.port=443
oauth.token.path=/as/token.oauth2
oauth.grant_type=password
oauth.username=![C/UZkcNT8O5Gu+dHIgRoAw==]
oauth.password=![4e8auv4HCDHZUsVoY0Bg5A==]
oauth.client_id=![qytc5sa5ZNxkdNB6xgYE3RfPFIPDH5vWklUOHLqm0dc=]
oauth.client_secret=![zdCXZjmqpx/xMdY/ZJtsthy93E5UkvpHqafmea5BwBZRu5TUXDvpVnDa69Wlu/MH80B4y6tl71d8Yi2NBrDJB+fpKJImr467gHWQF68kqnQ=]

# Backend API Configuration
api.host=api-ch-t.nonprod.pge.com
api.port=443
api.basePath=/customer-payplan-v3-papi/v3
api.basic.username=![iRliZdN7ka/A3xqdaJh3v6lj7t1AVHI1IMFpVG5b3q6N76u0bkGLhGihQ6Ez8+do]
api.basic.password=![xPAEjOiEK4LKoxqHXAowrCTE6azehC0aRXfi7KmmhwmiLHmhm0thuBFhyyfw9qjU]

# PayPlan Schedules SAPI Configuration
sapi.host=api-m-test.cloud.pge.com
sapi.port=443
sapi.basePath=/customer-payplan-ccb-v1-sapi/v1

# TLS Keystore Configuration
tls.keystore.path=tls/test/mulekeystore.p12
tls.keystore.password=![FPGsxuF1Yd04yTVzqr+/IQ==]
