# MCP Server Configuration
http.port=8081

# MCP Client Configuration
mcp.server.url=http://localhost:8081
mcp.client.http.port=8082

# Backend API Configuration
#api.host=api-ch-d.nonprod.pge.com
api.host=api-m-dev.cloud.pge.com
api.port=443
api.basePath=/customer-payplan-v3-papi/v3
