# PROD Environment Configuration

# OAuth Token Configuration
oauth.token.host=itiamping.cloud.pge.com
oauth.token.port=443
oauth.token.path=/as/token.oauth2
oauth.grant_type=password
oauth.username=![REPLACE_WITH_PROD_ENCRYPTED_VALUE]
oauth.password=![REPLACE_WITH_PROD_ENCRYPTED_VALUE]
oauth.client_id=![REPLACE_WITH_PROD_ENCRYPTED_VALUE]
oauth.client_secret=![REPLACE_WITH_PROD_ENCRYPTED_VALUE]

# Backend API Configuration
api.host=api-ch.ss.pge.com
api.port=443
api.basePath=/customer-payplan-v3-papi/v3
api.basic.username=![REPLACE_WITH_PROD_ENCRYPTED_VALUE]
api.basic.password=![REPLACE_WITH_PROD_ENCRYPTED_VALUE]

# PayPlan Schedules SAPI Configuration
sapi.host=api-m.cloud.pge.com
sapi.port=443
sapi.basePath=/customer-payplan-ccb-v1-sapi/v1

# TLS Keystore Configuration
tls.keystore.path=tls/prod/mulekeystore.p12
tls.keystore.password=![REPLACE_WITH_PROD_ENCRYPTED_VALUE]
