# MCP Server Configuration
# CloudHub 2.0 uses 8081 by default; override via system property if needed
http.port=8081

# MCP Client Configuration
# On CloudHub, use http://0.0.0.0:8081 to self-reference the app's own listener
mcp.server.url=http://0.0.0.0:8081
mcp.client.http.port=8082

# OAuth Token Configuration
oauth.token.host=itiampingqa.cloud.pge.com
oauth.token.port=443
oauth.token.path=/as/token.oauth2
oauth.grant_type=password
oauth.username=![C/UZkcNT8O5Gu+dHIgRoAw==]
oauth.password=![PtedZUYkSk9hgVY/5Xmbyw==]
#EI_IVR%40Mu13%23Use
oauth.client_id=![qytc5sa5ZNxkdNB6xgYE3RfPFIPDH5vWklUOHLqm0dc=]
oauth.client_secret=![dnqA9QBglI0ZAoyM3eNI4S3o1f5UqZ3wZ0/uvSwKAX5z3sUWq632VMPBlr3RGO6T7GO0ws5SJATDEjbgsGayWpH8DRwDQKFGFhOsq8qTJNE=]
#xCQ8FJbD4X52jP1icuSBMtQAqfWEDoac0rrFdnP5aztlswYmteoTH9dHns2n0Lln

# Backend API Configuration
#api.host=api-ch-d.nonprod.pge.com
api.host=api-ch-q.ss.pge.com
api.port=443
api.basePath=/customer-payplan-v3-papi/v3
api.basic.username=![iRliZdN7ka/A3xqdaJh3v6lj7t1AVHI1IMFpVG5b3q6N76u0bkGLhGihQ6Ez8+do]
api.basic.password=![xPAEjOiEK4LKoxqHXAowrCTE6azehC0aRXfi7KmmhwmiLHmhm0thuBFhyyfw9qjU]

# PayPlan Schedules SAPI Configuration
sapi.host=api-m-qa.cloud.pge.com
sapi.port=443
sapi.basePath=/customer-payplan-ccb-v1-sapi/v1
